version: '3.1'
services:
  stats-server:
    build: ./stats
    container_name: ewm_stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "6541:5432"

  ewm-service:
    build: ./main
    container_name: ewm_main
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm_main
      - STATS_SERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "6542:5432"
